account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import home,ArticleList

app_name = 'account'
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    # path("logout/", views.LogoutView.as_view(), name="logout"),
    # path(
    #     "password_change/", views.PasswordChangeView.as_view(), name="password_change"
    # ),
    # path(
    #     "password_change/done/",
    #     views.PasswordChangeDoneView.as_view(),
    #     name="password_change_done",
    # ),
    # path("password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    # path(
    #     "password_reset/done/",
    #     views.PasswordResetDoneView.as_view(),
    #     name="password_reset_done",
    # ),
    # path(
    #     "reset/<uidb64>/<token>/",
    #     views.PasswordResetConfirmView.as_view(),
    #     name="password_reset_confirm",
    # ),
    # path(
    #     "reset/done/",
    #     views.PasswordResetCompleteView.as_view(),
    #     name="password_reset_complete",
    # ),
]

urlpatterns += [
    # path("", home, name="home"),
    path("", ArticleList.as_view(), name="home"),
]

blog/urls.py
from django.urls import path
from .views import home, api, ArticleList, ArticleDetail,CategoryList

app_name = "blog"
urlpatterns = [
    path('/', home, name="home"),
    # path('home', home_from_database, name="home_from_database"),
    path('',ArticleList.as_view(), name="home_from_database"),
    # path('home/page/<int:page>', home_from_database, name="home_from_database"),
    # path('article/<slug:slug>', detail_article, name="detail"),
    path('article/<slug:slug>', ArticleDetail.as_view(), name="detail"),
    # path('category/<slug:slug>', category, name="category"),
    path('category/<slug:slug>', CategoryList.as_view(), name="category"),
    path('api', api, name="api")
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include

# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                     document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from extensions.utils import jalali_converter


# My managers

class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)


# Create your models here.

class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL,
                               related_name='children')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    status = models.BooleanField(default=True)
    position = models.IntegerField()
    thumbnail = models.ImageField(upload_to="images", default= "home-bg.jpg")

    # class Meta:
    #     verbose_name = "دسته بندی"
    #     verbose_name_plural = " دسته بندی ها"
    #     ordering = ['parent__id','position']

    def __str__(self):
        return self.title

    objects = CategoryManager()


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'default'),
        ('p', 'published'),
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    category = models.ManyToManyField(Category, related_name="articles")
    description = models.TextField()
    thumbnail = models.ImageField(upload_to="images")
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)

    def __str__(self):
        return self.title

    # def publish(self):
    #     return jalali_converter(self.publish)

    def category_published(self):
        return self.category.filter(status=True)

    objects = ArticleManager()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse \
    # ,Http404
from django.views.generic import ListView, DetailView

from blog.models import Article, Category


def home(request):
    context = {

        "user": [{"username": "fahimeh",
                  "age": 36,
                  "job": "programmer"}],
        "articles": [
            {
                "article": "تشخیص آفساید نیمه‌خودکار ",
                "description": "این فناوری بسیار شبیه به فناوری خط دروازه است، اما به جای ردیابی خط ثابت دروازه، به‌صورت پیوسته بازیکنان را دنبال می‌کند. این سیستم با کمک هوش مصنوعی به داوران بازی اجازه می‌دهد تا در سریع‌ترین زمان ممکن آفسایدها را تشخیص دهند.",
                "image": "https://digiato.com/wp-content/uploads/2022/11/fifafafafa-sXk4.jpg"
            },
            {
                "article": "توپ متصل به شبکه ",
                "description": "توپ رسمی جام جهانی امسال با نام «الرحله» در داخل خود یک حسگر کروی‌شکل دارد که 500 بار در هر ثانیه اطلاعات خود را به اتاق عملیات ویدیویی می‌فرستد و اجازه شناسایی نقطه دقیق شوت‌شدن را می‌دهد.",
                "image": "https://digiato.com/wp-content/uploads/2022/11/Cum-va-arata-mingea-cu-care-se-vor-juca-meciurile-de-la-Campionatul-Mondial-din-Qatar-inclusiv-cu-acel-senzor-in-ea.-Sursa-news.adidas.com_.jpg"
            },
            {
                "article": "فناوری‌های خنک‌کننده ",
                "description": "فیفا برای برگزاری جام جهانی در قطر مجبور شد این رقابت‌ها را حدود شش ماه به تعویق بیندازد و بازی‌ها را به جای تابستان در اواخر پاییز برگزار کند تا مشکلات ناشی از گرمای شدید در این کشور گریبان‌گیر بازیکنان و تماشاچیان نشود. با این حال، دمای هوا در قطر همچنان به‌طور میانگین بین 21 تا 26 درجه سلسیوس است.",
                "image": "https://digiato.com/wp-content/uploads/2022/11/original.jpeg"

            }]

    }
    return render(request, "blog/home0.html", context)


# def home_from_database(request):
#     article_list = Article.objects.published()
#     paginator = Paginator(article_list,1)
#     page = request.GET.get('page')
#     articles = paginator.get_page(page)
#     context = {
#         # "articles": Article.objects.all()
#         # "articles": Article.objects.filter(status="p").order_by("-publish")[:3]  # display 3 last article
#         # "articles": Article.objects.filter(status="p"),  # or #Article.objects.published() => with ArticleManager
#         "articles": articles,
#
#         # "category": Category.objects.filter(status=True)
#     }
#
#     return render(request, "blog/home_from_database.html", context)

class ArticleList(ListView):
    # model = Article
    template_name = 'blog/home_from_database.html'
    context_object_name = "articles"
    queryset = Article.objects.published()
    # paginate_by = 5


# def detail_article(request, slug):
#     # try:
#     #     article = Article.objects.get(slug = slug)
#     # except Exception as e:
#     #     raise Http404
#     # context = {
#     #     "article": article
#     #
#     # }
#
#     context = {
#         "article": get_object_or_404(Article, slug=slug, status="p"),
#         # or #get_object_or_404(Article.objects.published(), slug=slug)
#         # "category": Category.objects.filter(status=True)
#     }
#     return render(request, "blog/detail.html", context)

class ArticleDetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Article.objects.published(), slug=slug)


# def category(request, slug):
#     context = {
#         "category": get_object_or_404(Category, slug=slug, status=True),
#     }
#     return render(request, "blog/category.html", context)

class CategoryList(ListView):
    # paginate_by = 5
    template_name = 'blog/category_list.html'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


def api(request):
    data = {
        "1": {"title": "مقاله اول",
              "id": 20,
              "edition": "first_edition"},
        "2": {"title": "مقاله دوم",
              "id": 21,
              "edition": "second_edition"},
        "3": {"title": "مقاله سوم",
              "id": 22,
              "edition": "third_edition"}
    }
    return JsonResponse(data)

templates/blog/partials/category_list.html
{% extends 'blog/base.html' %}

{% load static %}

{% block main %}
<!-- Page Header-->
<header class="masthead" , padding-top = 15 ,style="background-image: url('{% static 'blog/assets/img/Plan-a-Trip-Vacation-Math-Problem.png' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1></h1>
                    <span class="subheading"></span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <h3 class="alert alert-primary text-center">دسته بندی : {{ category.title}}</h3>
            {% for article in category.articles.published %}
            <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'blog:detail' article.slug %}">
                    <h2 class="post-title">{{ article.title }}</h2>
                    <h3 class="post-subtitle">{{ article.description | truncatewords:10 }}</h3>

                </a>
                <p class="post-meta">

                    <a href="#!"></a>
                <h4 class="post-subtitle">{{ article.publish }}</h4>
                <div>
                    {% for cat in article.category_published.all %}
                    <a href = "#"> #{{ cat.title }}</a>

                    {% endfor %}
                    </div>
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4"/>

            <hr class="my-4"/>
            {% endfor %}
            <!-- Pager-->

        </div>
    </div>
</div>
{% endblock %}

templates/blog/partials/category_navbar.html
<div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ms-auto py-4 py-lg-0">
<!--        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4"-->
<!--                                href="{% url 'blog:home_from_database' %}">Home</a></li>-->

        {% for cat in category %}

        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:category' cat.slug %}">{{cat.title }}</a></li>

        {% endfor %}

    </ul>
<!--    <li class="nav-item"><a href="{% url 'account:login' %}">Login</a></li>-->
</div>